export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";


export const REGISTER_USER_REQUEST="REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL="REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST="LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS="LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL="LOAD_USER_FAIL";

export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const IMAGE_REQUEST = "IMAGE_REQUEST";
export const IMAGE_SUCCESS = "IMAGE_SUCCESS";
export const IMAGE_FAILURE = "IMAGE_FAILURE";
export const IMAGE_RESET = "IMAGE_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_IMAGES_REQUEST = "IMAGE_REQUEST";
export const GET_IMAGES_SUCCESS = "IMAGE_SUCCESS";
export const GET_IMAGES_FAILURE = "IMAGE_FAILURE";